### ISSUE TITLE
Cocos creator 2.1.1 报错

### ISSUE THREAD

**Issue by Sunbvert** [fylz1125/ShaderDemos#7]
用Cocos Creator打开项目后报以下错误，为什么呢？

```
load script [/Users/sunbvert/Downloads/ShaderDemos-master/temp/quick-scripts/assets/Script/shader/ShaderMaterial.js] failed : TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>)
    at extendStatics (/Users/sunbvert/Downloads/ShaderDemos-master/temp/quick-scripts/assets/Script/shader/ShaderMaterial.js:11:16)
    at __extends (/Users/sunbvert/Downloads/ShaderDemos-master/temp/quick-scripts/assets/Script/shader/ShaderMaterial.js:14:9)
    at /Users/sunbvert/Downloads/ShaderDemos-master/temp/quick-scripts/assets/Script/shader/ShaderMaterial.js:23:5
    at __define (/Users/sunbvert/Downloads/ShaderDemos-master/temp/quick-scripts/assets/Script/shader/ShaderMaterial.js:95:2)
    at /Users/sunbvert/Downloads/ShaderDemos-master/temp/quick-scripts/assets/Script/shader/ShaderMaterial.js:101:13
    at Object.<anonymous> (/Users/sunbvert/Downloads/ShaderDemos-master/temp/quick-scripts/assets/Script/shader/ShaderMaterial.js:108:11)
    at Object.<anonymous> (/Users/sunbvert/Downloads/ShaderDemos-master/temp/quick-scripts/assets/Script/shader/ShaderMaterial.js:111:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
```

**Comment by fylz1125** [comment]
2.1.1版本还没有改完，敬请关注

**Comment by kingkamg** [comment]
汗，还没改完呢，都2.1.2了

**Comment by WATS1BZ** [comment]
大佬，2.1.1还有多久出来呢？
萌新请假下，从2.0.6到2.1.1是什么原因导致无法运行呢？

**Comment by CocosGames** [comment]
up主自挂东南枝了吗

**Comment by fylz1125** [comment]
为了做一个技术平台，导致了开源项目不能按时更新，抱歉

> up主自挂东南枝了吗

**Comment by fylz1125** [comment]
> 大佬，2.1.1还有多久出来呢？
> 萌新请假下，从2.0.6到2.1.1是什么原因导致无法运行呢？

马上2.0和2.1,2.2一起更新，大部分功能都已经写完了。
由于引擎官方，重新设计了shader渲染接口，2.1以后采用新设计的材质系统，为了向3d过渡，导致以前偏opengl的接口无法使用，然而官方又没有文档，需要看引擎源码，请教他们才能重写这个
